create table propositions (
        id integer generated by default as identity (start with 1),
        correct boolean not null,
        explanation clob(255),
        question_id integer,
        statement varchar(255),
        primary key (id)
    );
create table questions (
        id integer generated by default as identity (start with 1),
        level integer,
        statement clob(255),
        topic_id integer,
        primary key (id)
    );
create table results (
        id integer generated by default as identity (start with 1),
        valid boolean not null,
        answer_id integer,
        question_id integer,
        user_id integer,
        primary key (id)
    );
create table ROLES (
        id integer generated by default as identity (start with 1),
        name varchar(255),
        primary key (id)
    );
create table topics (
        id integer generated by default as identity (start with 1),
        name varchar(255),
        primary key (id)
        );
create table USERS (
        id integer generated by default as identity (start with 1),
        createdAt timestamp,
        enabled boolean not null,
        firstname varchar(255),
        lastname varchar(255),
        login varchar(255),
        password varchar(255),
        updatedAt timestamp,
        primary key (id)
    );
create table users_roles (
        user_id integer not null,
        role_id integer not null,
        primary key (user_id, role_id)
    );

alter table propositions 
        add constraint FK73rlf91a0ri0yin9ndo7il0 
        foreign key (question_id) 
        references questions;
alter table questions 
        add constraint FKdb5p6ukb0v76he4pq87cbymhg 
        foreign key (topic_id) 
        references topics;
alter table results 
        add constraint FK54vy8hbk0yl014b8p57buca8o 
        foreign key (answer_id) 
        references propositions;
alter table results 
        add constraint FKmaebl47qyt3rnoibgpkovjwgg 
        foreign key (question_id) 
        references questions;
alter table results 
        add constraint FK17pkdvgb94uejeqddnyaqc9rn 
        foreign key (user_id) 
        references USERS;
alter table users_roles 
        add constraint FKh9bs29w8mwo0yc2o3xi7me0nq 
        foreign key (role_id) 
        references ROLES;
alter table users_roles 
        add constraint FKn9697al5cfs6rqy40ft93wgc5 
        foreign key (user_id) 
        references USERS;